name = 'Live CV'
license = 'MIT'
licenselink = 'https://github.com/ziruifan/hugo-theme-live-cv/LICENSE'
description = 'An online CV theme for Hugo'

homepage = 'https://github.com/ziruifan/hugo-theme-live-cv'

demosite = 'https://ziruifan.github.io/hugo-theme-live-cv'

[author]
  name = 'Fan Zirui'
  homepage = 'zirui.fun'
